version: "3.7"
services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_DB: "CumPostBot"
      POSTGRES_USER: "CumPostBot"
      POSTGRES_PASSWORD: "Cum*Post*Bot*"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--requirepass ${REDIS_PASS:-password123}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/user/local/etc/redis/redis.conf

volumes:
  redis-data:
  redis-conf: