version: "3.7"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "CumPostBot"
      POSTGRES_USER: "CumPostBot"
      POSTGRES_PASSWORD: "Cum*Post*Bot*"
#    volumes:
#      - ./docker_data/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"